// ============================================
// 內容資料：單字庫 + 閱讀短文
// 之後要新增內容，直接在下面陣列加入新物件即可
// ============================================

const UNITS = [
  { id: "daily",   name: "日常生活" },
  { id: "school",  name: "學校與學習" },
  { id: "food",    name: "飲食" },
  { id: "travel",  name: "旅遊" },
  { id: "feelings",name: "情緒與個性" },
  { id: "work",    name: "工作與未來" },
  { id: "health",  name: "健康身體" },
  { id: "tech",    name: "科技" },
  { id: "shopping",name: "購物" },
  { id: "nature",  name: "天氣與自然" },
  { id: "relationships", name: "人際關係" },
  { id: "entertainment", name: "娛樂" },
];

const VOCAB = [
  // ---- 日常生活 ----
  { id:"routine", word:"routine", pos:"n.", zh:"例行公事、日常慣例", example:"Brushing your teeth every morning is part of your routine.", unit:"daily" },
  { id:"alarm", word:"alarm", pos:"n.", zh:"鬧鐘、警報", example:"My alarm goes off at seven every day.", unit:"daily" },
  { id:"breakfast", word:"breakfast", pos:"n.", zh:"早餐", example:"I never skip breakfast before work.", unit:"daily" },
  { id:"laundry", word:"laundry", pos:"n.", zh:"待洗衣物、洗衣", example:"I do the laundry every Sunday.", unit:"daily" },
  { id:"chores", word:"chores", pos:"n.", zh:"家務事", example:"Washing dishes is one of my daily chores.", unit:"daily" },
  { id:"exhausted", word:"exhausted", pos:"adj.", zh:"筋疲力盡的", example:"After the long meeting, she felt exhausted.", unit:"daily" },
  { id:"commute", word:"commute", pos:"n./v.", zh:"通勤", example:"My commute to work takes about forty minutes.", unit:"daily" },
  { id:"errand", word:"errand", pos:"n.", zh:"outing/跑腿、雜事", example:"I need to run an errand before lunch.", unit:"daily" },
  { id:"habit", word:"habit", pos:"n.", zh:"習慣", example:"Reading before bed is a good habit.", unit:"daily" },
  { id:"grocery", word:"grocery", pos:"n.", zh:"雜貨（食品）", example:"We go grocery shopping every weekend.", unit:"daily" },
  { id:"appointment", word:"appointment", pos:"n.", zh:"約會、預約", example:"I have a dentist appointment tomorrow.", unit:"daily" },
  { id:"schedule", word:"schedule", pos:"n.", zh:"時間表、行程", example:"My schedule is full this week.", unit:"daily" },
  { id:"relax", word:"relax", pos:"v.", zh:"放鬆", example:"I like to relax by listening to music.", unit:"daily" },
  { id:"tidy", word:"tidy", pos:"adj./v.", zh:"整齊的、整理", example:"She always keeps her room tidy.", unit:"daily" },
  { id:"neighbor", word:"neighbor", pos:"n.", zh:"鄰居", example:"My neighbor is very friendly.", unit:"daily" },
  { id:"apartment", word:"apartment", pos:"n.", zh:"公寓", example:"They just moved into a new apartment.", unit:"daily" },
  { id:"furniture", word:"furniture", pos:"n.", zh:"家具", example:"We bought some new furniture for the living room.", unit:"daily" },
  { id:"electricity", word:"electricity", pos:"n.", zh:"電力", example:"The electricity went out during the storm.", unit:"daily" },
  { id:"garbage", word:"garbage", pos:"n.", zh:"垃圾", example:"Please take out the garbage tonight.", unit:"daily" },
  { id:"weekday", word:"weekday", pos:"n.", zh:"平日（週一到五）", example:"I work from Monday to Friday, every weekday.", unit:"daily" },

  // ---- 學校與學習 ----
  { id:"assignment", word:"assignment", pos:"n.", zh:"作業、任務", example:"Our teacher gave us a difficult assignment today.", unit:"school" },
  { id:"lecture", word:"lecture", pos:"n.", zh:"講課、演講", example:"The professor's lecture lasted two hours.", unit:"school" },
  { id:"semester", word:"semester", pos:"n.", zh:"學期", example:"This semester has been very busy.", unit:"school" },
  { id:"textbook", word:"textbook", pos:"n.", zh:"教科書", example:"Please open your textbook to page ten.", unit:"school" },
  { id:"classmate", word:"classmate", pos:"n.", zh:"同班同學", example:"My classmate helped me with my homework.", unit:"school" },
  { id:"review", word:"review", pos:"v./n.", zh:"複習、評論", example:"I need to review this chapter before the test.", unit:"school" },
  { id:"exam", word:"exam", pos:"n.", zh:"考試", example:"The final exam covers the whole semester.", unit:"school" },
  { id:"grade", word:"grade", pos:"n.", zh:"成績、年級", example:"She got a good grade on her essay.", unit:"school" },
  { id:"focus", word:"focus", pos:"v./n.", zh:"專注", example:"It's hard to focus with so much noise.", unit:"school" },
  { id:"memorize", word:"memorize", pos:"v.", zh:"背誦、記住", example:"I memorize ten new words every day.", unit:"school" },
  { id:"dictionary", word:"dictionary", pos:"n.", zh:"字典", example:"You can check the word in a dictionary.", unit:"school" },
  { id:"essay", word:"essay", pos:"n.", zh:"文章、作文", example:"We have to write a 500-word essay.", unit:"school" },
  { id:"presentation", word:"presentation", pos:"n.", zh:"報告、簡報", example:"My presentation is scheduled for next Monday.", unit:"school" },
  { id:"deadline", word:"deadline", pos:"n.", zh:"截止日期", example:"The deadline for the report is Friday.", unit:"school" },
  { id:"notebook", word:"notebook", pos:"n.", zh:"筆記本", example:"I write new vocabulary in my notebook.", unit:"school" },
  { id:"principal", word:"principal", pos:"n.", zh:"校長", example:"The principal gave a speech this morning.", unit:"school" },
  { id:"subject", word:"subject", pos:"n.", zh:"科目、主題", example:"Math is my favorite subject.", unit:"school" },
  { id:"skill", word:"skill", pos:"n.", zh:"技能", example:"Speaking English well is a useful skill.", unit:"school" },
  { id:"improve", word:"improve", pos:"v.", zh:"改善、進步", example:"Practicing daily will improve your speaking.", unit:"school" },
  { id:"motivation", word:"motivation", pos:"n.", zh:"動機、動力", example:"I lost my motivation to study after the exam.", unit:"school" },

  // ---- 飲食 ----
  { id:"recipe", word:"recipe", pos:"n.", zh:"食譜", example:"She found the recipe online.", unit:"food" },
  { id:"ingredient", word:"ingredient", pos:"n.", zh:"食材、原料", example:"Fresh vegetables are the main ingredient in this dish.", unit:"food" },
  { id:"delicious", word:"delicious", pos:"adj.", zh:"美味的", example:"This soup is absolutely delicious.", unit:"food" },
  { id:"flavor", word:"flavor", pos:"n.", zh:"味道、風味", example:"I love the flavor of fresh basil.", unit:"food" },
  { id:"leftover", word:"leftover", pos:"n./adj.", zh:"剩菜、剩下的", example:"We had leftover rice for lunch.", unit:"food" },
  { id:"appetite", word:"appetite", pos:"n.", zh:"食慾", example:"Exercise usually gives me a big appetite.", unit:"food" },
  { id:"restaurant", word:"restaurant", pos:"n.", zh:"餐廳", example:"We ate at a new restaurant last night.", unit:"food" },
  { id:"reservation", word:"reservation", pos:"n.", zh:"預約、訂位", example:"I made a reservation for two people at seven.", unit:"food" },
  { id:"portion", word:"portion", pos:"n.", zh:"份量", example:"The portion at this restaurant is quite large.", unit:"food" },
  { id:"dessert", word:"dessert", pos:"n.", zh:"甜點", example:"We shared a chocolate cake for dessert.", unit:"food" },
  { id:"spicy", word:"spicy", pos:"adj.", zh:"辣的", example:"This dish is a little too spicy for me.", unit:"food" },
  { id:"fresh", word:"fresh", pos:"adj.", zh:"新鮮的", example:"The fish at the market looks very fresh.", unit:"food" },
  { id:"menu", word:"menu", pos:"n.", zh:"菜單", example:"Can I see the menu, please?", unit:"food" },
  { id:"waiter", word:"waiter", pos:"n.", zh:"服務生", example:"The waiter recommended the fish soup.", unit:"food" },
  { id:"bill", word:"bill", pos:"n.", zh:"帳單", example:"Could we have the bill, please?", unit:"food" },
  { id:"takeout", word:"takeout", pos:"n.", zh:"外帶", example:"Let's just order takeout tonight.", unit:"food" },
  { id:"snack", word:"snack", pos:"n.", zh:"點心、零食", example:"I usually have a snack in the afternoon.", unit:"food" },
  { id:"nutrition", word:"nutrition", pos:"n.", zh:"營養", example:"Good nutrition helps you stay healthy.", unit:"food" },
  { id:"diet", word:"diet", pos:"n.", zh:"飲食（習慣）", example:"She is trying to eat a balanced diet.", unit:"food" },
  { id:"craving", word:"craving", pos:"n.", zh:"渴望（食物）", example:"I have a craving for chocolate right now.", unit:"food" },

  // ---- 旅遊 ----
  { id:"journey", word:"journey", pos:"n.", zh:"旅程", example:"Our journey to the mountains took six hours.", unit:"travel" },
  { id:"itinerary", word:"itinerary", pos:"n.", zh:"行程表", example:"I planned our itinerary for the whole trip.", unit:"travel" },
  { id:"luggage", word:"luggage", pos:"n.", zh:"行李", example:"Please don't leave your luggage unattended.", unit:"travel" },
  { id:"passport", word:"passport", pos:"n.", zh:"護照", example:"Make sure your passport hasn't expired.", unit:"travel" },
  { id:"destination", word:"destination", pos:"n.", zh:"目的地", example:"Our final destination is a small island.", unit:"travel" },
  { id:"souvenir", word:"souvenir", pos:"n.", zh:"紀念品", example:"I bought a small souvenir for my sister.", unit:"travel" },
  { id:"accommodation", word:"accommodation", pos:"n.", zh:"住宿", example:"We booked our accommodation near the beach.", unit:"travel" },
  { id:"transportation", word:"transportation", pos:"n.", zh:"交通、運輸", example:"Public transportation here is very convenient.", unit:"travel" },
  { id:"sightseeing", word:"sightseeing", pos:"n.", zh:"觀光", example:"We spent the whole day sightseeing.", unit:"travel" },
  { id:"adventure", word:"adventure", pos:"n.", zh:"冒險", example:"Backpacking alone was a real adventure.", unit:"travel" },
  { id:"delay", word:"delay", pos:"n./v.", zh:"延誤、延遲", example:"Our flight had a two-hour delay.", unit:"travel" },
  { id:"boarding", word:"boarding", pos:"n.", zh:"登機、登船", example:"Boarding starts thirty minutes before departure.", unit:"travel" },
  { id:"currency", word:"currency", pos:"n.", zh:"貨幣", example:"I need to exchange some local currency.", unit:"travel" },
  { id:"local", word:"local", pos:"adj./n.", zh:"當地的、當地人", example:"We asked a local for directions.", unit:"travel" },
  { id:"scenery", word:"scenery", pos:"n.", zh:"風景", example:"The scenery along the coast was beautiful.", unit:"travel" },
  { id:"backpack", word:"backpack", pos:"n.", zh:"背包", example:"I always travel with just a small backpack.", unit:"travel" },
  { id:"guide", word:"guide", pos:"n.", zh:"導遊、指南", example:"Our guide showed us the old temple.", unit:"travel" },
  { id:"explore", word:"explore", pos:"v.", zh:"探索", example:"We spent the morning exploring the old town.", unit:"travel" },
  { id:"culture", word:"culture", pos:"n.", zh:"文化", example:"I love learning about different cultures.", unit:"travel" },
  { id:"jet lag", word:"jet lag", pos:"n.", zh:"時差", example:"It took me two days to recover from jet lag.", unit:"travel" },

  // ---- 情緒與個性 ----
  { id:"nervous", word:"nervous", pos:"adj.", zh:"緊張的", example:"I always feel nervous before a test.", unit:"feelings" },
  { id:"confident", word:"confident", pos:"adj.", zh:"有自信的", example:"She looked confident during the interview.", unit:"feelings" },
  { id:"curious", word:"curious", pos:"adj.", zh:"好奇的", example:"Kids are naturally curious about the world.", unit:"feelings" },
  { id:"patient", word:"patient", pos:"adj.", zh:"有耐心的", example:"You need to be patient with beginners.", unit:"feelings" },
  { id:"stubborn", word:"stubborn", pos:"adj.", zh:"固執的", example:"My grandfather can be very stubborn.", unit:"feelings" },
  { id:"generous", word:"generous", pos:"adj.", zh:"慷慨的", example:"It was generous of him to share his lunch.", unit:"feelings" },
  { id:"jealous", word:"jealous", pos:"adj.", zh:"嫉妒的", example:"He felt jealous when his friend got the job.", unit:"feelings" },
  { id:"embarrassed", word:"embarrassed", pos:"adj.", zh:"尷尬的", example:"I felt embarrassed after forgetting his name.", unit:"feelings" },
  { id:"grateful", word:"grateful", pos:"adj.", zh:"感激的", example:"I'm grateful for all your help.", unit:"feelings" },
  { id:"anxious", word:"anxious", pos:"adj.", zh:"焦慮的", example:"She felt anxious about the results.", unit:"feelings" },
  { id:"cheerful", word:"cheerful", pos:"adj.", zh:"開朗愉快的", example:"He is always cheerful in the morning.", unit:"feelings" },
  { id:"honest", word:"honest", pos:"adj.", zh:"誠實的", example:"Please be honest about how you feel.", unit:"feelings" },
  { id:"shy", word:"shy", pos:"adj.", zh:"害羞的", example:"She was too shy to speak in front of the class.", unit:"feelings" },
  { id:"ambitious", word:"ambitious", pos:"adj.", zh:"有野心的、有抱負的", example:"He is ambitious and wants to start his own company.", unit:"feelings" },
  { id:"sensitive", word:"sensitive", pos:"adj.", zh:"敏感的", example:"She is quite sensitive to criticism.", unit:"feelings" },
  { id:"optimistic", word:"optimistic", pos:"adj.", zh:"樂觀的", example:"Try to stay optimistic about the future.", unit:"feelings" },
  { id:"disappointed", word:"disappointed", pos:"adj.", zh:"失望的", example:"I was disappointed with the movie.", unit:"feelings" },
  { id:"proud", word:"proud", pos:"adj.", zh:"驕傲的、自豪的", example:"My parents are proud of my progress.", unit:"feelings" },
  { id:"lonely", word:"lonely", pos:"adj.", zh:"孤單的", example:"Moving to a new city can feel lonely at first.", unit:"feelings" },
  { id:"calm", word:"calm", pos:"adj.", zh:"冷靜的", example:"Try to stay calm during the interview.", unit:"feelings" },

  // ---- 工作與未來 ----
  { id:"career", word:"career", pos:"n.", zh:"職涯、事業", example:"She wants to build a career in design.", unit:"work" },
  { id:"interview", word:"interview", pos:"n./v.", zh:"面試", example:"I have a job interview tomorrow morning.", unit:"work" },
  { id:"resume", word:"resume", pos:"n.", zh:"履歷表", example:"I updated my resume before applying.", unit:"work" },
  { id:"salary", word:"salary", pos:"n.", zh:"薪水", example:"The job offers a good starting salary.", unit:"work" },
  { id:"promotion", word:"promotion", pos:"n.", zh:"升遷", example:"He got a promotion after two years.", unit:"work" },
  { id:"colleague", word:"colleague", pos:"n.", zh:"同事", example:"My colleagues are very supportive.", unit:"work" },
  { id:"responsibility", word:"responsibility", pos:"n.", zh:"責任", example:"Taking care of the budget is my responsibility.", unit:"work" },
  { id:"experience", word:"experience", pos:"n.", zh:"經驗", example:"This internship gave me valuable experience.", unit:"work" },
  { id:"opportunity", word:"opportunity", pos:"n.", zh:"機會", example:"This job is a great opportunity for me.", unit:"work" },
  { id:"goal", word:"goal", pos:"n.", zh:"目標", example:"My goal is to become a project manager.", unit:"work" },
  { id:"achievement", word:"achievement", pos:"n.", zh:"成就", example:"Graduating early was a big achievement for her.", unit:"work" },
  { id:"challenge", word:"challenge", pos:"n.", zh:"挑戰", example:"Learning a new language is always a challenge.", unit:"work" },
  { id:"teamwork", word:"teamwork", pos:"n.", zh:"團隊合作", example:"Good teamwork made the project finish early.", unit:"work" },
  { id:"ambition", word:"ambition", pos:"n.", zh:"抱負、雄心", example:"Her ambition is to open her own restaurant.", unit:"work" },
  { id:"negotiate", word:"negotiate", pos:"v.", zh:"談判、協商", example:"You can try to negotiate a higher salary.", unit:"work" },
  { id:"internship", word:"internship", pos:"n.", zh:"實習", example:"She did an internship at a marketing company.", unit:"work" },
  { id:"qualification", word:"qualification", pos:"n.", zh:"資格、資歷", example:"You need a teaching qualification for this job.", unit:"work" },
  { id:"leadership", word:"leadership", pos:"n.", zh:"領導力", example:"The manager showed strong leadership during the crisis.", unit:"work" },
  { id:"network", word:"network", pos:"n./v.", zh:"人脈、建立關係網", example:"Networking helped him find his current job.", unit:"work" },
  { id:"flexible", word:"flexible", pos:"adj.", zh:"有彈性的", example:"This company offers flexible working hours.", unit:"work" },

  // ---- 健康身體 ----
  { id:"symptom", word:"symptom", pos:"n.", zh:"症狀", example:"A sore throat is a common symptom of a cold.", unit:"health" },
  { id:"headache", word:"headache", pos:"n.", zh:"頭痛", example:"I have a bad headache today.", unit:"health" },
  { id:"fever", word:"fever", pos:"n.", zh:"發燒", example:"She stayed home because she had a fever.", unit:"health" },
  { id:"prescription", word:"prescription", pos:"n.", zh:"處方箋", example:"The doctor gave me a prescription for antibiotics.", unit:"health" },
  { id:"pharmacy", word:"pharmacy", pos:"n.", zh:"藥局", example:"I picked up my medicine at the pharmacy.", unit:"health" },
  { id:"exercise", word:"exercise", pos:"n./v.", zh:"運動", example:"Regular exercise keeps you healthy.", unit:"health" },
  { id:"sleep", word:"sleep", pos:"n./v.", zh:"睡眠、睡覺", example:"Getting enough sleep improves your memory.", unit:"health" },
  { id:"stress", word:"stress", pos:"n.", zh:"壓力", example:"Too much stress can affect your health.", unit:"health" },
  { id:"injury", word:"injury", pos:"n.", zh:"傷害、受傷", example:"He got a minor injury while playing basketball.", unit:"health" },
  { id:"recover", word:"recover", pos:"v.", zh:"恢復、康復", example:"It took two weeks for her to recover from the flu.", unit:"health" },
  { id:"checkup", word:"checkup", pos:"n.", zh:"健康檢查", example:"I have a yearly checkup at the clinic.", unit:"health" },
  { id:"allergy", word:"allergy", pos:"n.", zh:"過敏", example:"He has an allergy to peanuts.", unit:"health" },
  { id:"vitamin", word:"vitamin", pos:"n.", zh:"維他命", example:"Oranges are a good source of vitamin C.", unit:"health" },
  { id:"posture", word:"posture", pos:"n.", zh:"姿勢、姿態", example:"Sitting up straight improves your posture.", unit:"health" },
  { id:"hydrate", word:"hydrate", pos:"v.", zh:"補充水分", example:"Remember to hydrate during exercise.", unit:"health" },
  { id:"immune", word:"immune", pos:"adj.", zh:"免疫的", example:"A healthy diet supports your immune system.", unit:"health" },
  { id:"diagnosis", word:"diagnosis", pos:"n.", zh:"診斷", example:"The doctor's diagnosis was a mild infection.", unit:"health" },
  { id:"treatment", word:"treatment", pos:"n.", zh:"治療", example:"The treatment lasted about a month.", unit:"health" },
  { id:"therapy", word:"therapy", pos:"n.", zh:"治療、療程", example:"She goes to physical therapy twice a week.", unit:"health" },
  { id:"wellness", word:"wellness", pos:"n.", zh:"健康、幸福感", example:"The company started a new wellness program.", unit:"health" },

  // ---- 科技 ----
  { id:"device", word:"device", pos:"n.", zh:"裝置、設備", example:"This device can track your daily steps.", unit:"tech" },
  { id:"software", word:"software", pos:"n.", zh:"軟體", example:"We need to install new software on this computer.", unit:"tech" },
  { id:"application", word:"application", pos:"n.", zh:"應用程式、申請", example:"I downloaded a new application for taking notes.", unit:"tech" },
  { id:"password", word:"password", pos:"n.", zh:"密碼", example:"Please don't share your password with anyone.", unit:"tech" },
  { id:"upload", word:"upload", pos:"v.", zh:"上傳", example:"I need to upload these photos to the cloud.", unit:"tech" },
  { id:"download", word:"download", pos:"v.", zh:"下載", example:"You can download the app for free.", unit:"tech" },
  { id:"battery", word:"battery", pos:"n.", zh:"電池", example:"My phone's battery dies quickly.", unit:"tech" },
  { id:"charger", word:"charger", pos:"n.", zh:"充電器", example:"I forgot my charger at home.", unit:"tech" },
  { id:"wireless", word:"wireless", pos:"adj.", zh:"無線的", example:"This keyboard connects wirelessly to my laptop.", unit:"tech" },
  { id:"update", word:"update", pos:"n./v.", zh:"更新", example:"There's a new software update available.", unit:"tech" },
  { id:"backup", word:"backup", pos:"n.", zh:"備份", example:"Always keep a backup of your important files.", unit:"tech" },
  { id:"malware", word:"malware", pos:"n.", zh:"惡意軟體", example:"This antivirus program can detect malware.", unit:"tech" },
  { id:"browser", word:"browser", pos:"n.", zh:"瀏覽器", example:"Chrome is a popular web browser.", unit:"tech" },
  { id:"screen", word:"screen", pos:"n.", zh:"螢幕", example:"The screen cracked when I dropped my phone.", unit:"tech" },
  { id:"keyboard", word:"keyboard", pos:"n.", zh:"鍵盤", example:"I bought a new mechanical keyboard.", unit:"tech" },
  { id:"notification", word:"notification", pos:"n.", zh:"通知", example:"I get too many notifications from that app.", unit:"tech" },
  { id:"storage", word:"storage", pos:"n.", zh:"儲存空間", example:"My phone is out of storage space.", unit:"tech" },
  { id:"bandwidth", word:"bandwidth", pos:"n.", zh:"頻寬", example:"Our home internet doesn't have much bandwidth.", unit:"tech" },
  { id:"streaming", word:"streaming", pos:"n.", zh:"串流", example:"We watched a movie on a streaming service.", unit:"tech" },
  { id:"virtual", word:"virtual", pos:"adj.", zh:"虛擬的", example:"We had a virtual meeting instead of an in-person one.", unit:"tech" },

  // ---- 購物 ----
  { id:"discount", word:"discount", pos:"n.", zh:"折扣", example:"I got a 20% discount on this jacket.", unit:"shopping" },
  { id:"coupon", word:"coupon", pos:"n.", zh:"折價券", example:"She used a coupon to save money.", unit:"shopping" },
  { id:"checkout", word:"checkout", pos:"n.", zh:"結帳", example:"There was a long line at the checkout.", unit:"shopping" },
  { id:"receipt", word:"receipt", pos:"n.", zh:"收據", example:"Please keep your receipt in case you need a refund.", unit:"shopping" },
  { id:"refund", word:"refund", pos:"n./v.", zh:"退款", example:"The store gave me a full refund.", unit:"shopping" },
  { id:"exchange", word:"exchange", pos:"n./v.", zh:"換貨、交換", example:"I want to exchange this shirt for a bigger size.", unit:"shopping" },
  { id:"warehouse", word:"warehouse", pos:"n.", zh:"倉庫", example:"The shoes are shipped directly from the warehouse.", unit:"shopping" },
  { id:"bargain", word:"bargain", pos:"n.", zh:"划算的交易", example:"This laptop was a real bargain.", unit:"shopping" },
  { id:"brand", word:"brand", pos:"n.", zh:"品牌", example:"This is my favorite clothing brand.", unit:"shopping" },
  { id:"quality", word:"quality", pos:"n.", zh:"品質", example:"The quality of this bag is excellent.", unit:"shopping" },
  { id:"customer", word:"customer", pos:"n.", zh:"顧客", example:"The customer asked for a different size.", unit:"shopping" },
  { id:"cashier", word:"cashier", pos:"n.", zh:"收銀員", example:"The cashier gave me my change.", unit:"shopping" },
  { id:"inventory", word:"inventory", pos:"n.", zh:"庫存", example:"The store is low on inventory this week.", unit:"shopping" },
  { id:"delivery", word:"delivery", pos:"n.", zh:"外送、配送", example:"The delivery usually takes three days.", unit:"shopping" },
  { id:"package", word:"package", pos:"n.", zh:"包裹", example:"I'm waiting for a package from the post office.", unit:"shopping" },
  { id:"subscription", word:"subscription", pos:"n.", zh:"訂閱", example:"I have a monthly subscription to that magazine.", unit:"shopping" },
  { id:"wholesale", word:"wholesale", pos:"adj./n.", zh:"批發", example:"They sell products at wholesale prices.", unit:"shopping" },
  { id:"retail", word:"retail", pos:"adj./n.", zh:"零售", example:"The retail price is higher than online.", unit:"shopping" },
  { id:"budget", word:"budget", pos:"n.", zh:"預算", example:"I'm trying to stay within my budget this month.", unit:"shopping" },
  { id:"purchase", word:"purchase", pos:"n./v.", zh:"購買", example:"I made a big purchase last weekend.", unit:"shopping" },

  // ---- 天氣與自然 ----
  { id:"humid", word:"humid", pos:"adj.", zh:"潮濕悶熱的", example:"Summers here are very humid.", unit:"nature" },
  { id:"drought", word:"drought", pos:"n.", zh:"乾旱", example:"The drought lasted for several months.", unit:"nature" },
  { id:"thunderstorm", word:"thunderstorm", pos:"n.", zh:"雷雨", example:"A thunderstorm is expected this afternoon.", unit:"nature" },
  { id:"breeze", word:"breeze", pos:"n.", zh:"微風", example:"A cool breeze made the walk pleasant.", unit:"nature" },
  { id:"temperature", word:"temperature", pos:"n.", zh:"溫度", example:"The temperature dropped suddenly last night.", unit:"nature" },
  { id:"forecast", word:"forecast", pos:"n.", zh:"預報", example:"The weather forecast says it will rain tomorrow.", unit:"nature" },
  { id:"flood", word:"flood", pos:"n./v.", zh:"洪水", example:"The flood damaged many homes near the river.", unit:"nature" },
  { id:"earthquake", word:"earthquake", pos:"n.", zh:"地震", example:"A small earthquake shook the city last week.", unit:"nature" },
  { id:"habitat", word:"habitat", pos:"n.", zh:"棲息地", example:"Cutting down forests destroys animal habitats.", unit:"nature" },
  { id:"pollution", word:"pollution", pos:"n.", zh:"污染", example:"Air pollution is a serious problem in big cities.", unit:"nature" },
  { id:"recycle", word:"recycle", pos:"v.", zh:"回收", example:"We recycle paper and plastic at home.", unit:"nature" },
  { id:"sustainable", word:"sustainable", pos:"adj.", zh:"永續的", example:"The company switched to sustainable packaging.", unit:"nature" },
  { id:"ecosystem", word:"ecosystem", pos:"n.", zh:"生態系統", example:"Coral reefs support a rich ecosystem.", unit:"nature" },
  { id:"climate", word:"climate", pos:"n.", zh:"氣候", example:"The island has a warm, tropical climate.", unit:"nature" },
  { id:"drizzle", word:"drizzle", pos:"n./v.", zh:"毛毛雨", example:"It was just a light drizzle, so we didn't need an umbrella.", unit:"nature" },
  { id:"blizzard", word:"blizzard", pos:"n.", zh:"暴風雪", example:"The blizzard closed all the schools.", unit:"nature" },
  { id:"harvest", word:"harvest", pos:"n./v.", zh:"收成、收割", example:"Farmers celebrate after a good harvest.", unit:"nature" },
  { id:"tide", word:"tide", pos:"n.", zh:"潮汐", example:"We checked the tide before going to the beach.", unit:"nature" },
  { id:"volcano", word:"volcano", pos:"n.", zh:"火山", example:"The volcano hasn't erupted in a hundred years.", unit:"nature" },
  { id:"wildlife", word:"wildlife", pos:"n.", zh:"野生動物", example:"The national park protects local wildlife.", unit:"nature" },

  // ---- 人際關係 ----
  { id:"relationship", word:"relationship", pos:"n.", zh:"關係", example:"They have a close relationship.", unit:"relationships" },
  { id:"trust", word:"trust", pos:"n./v.", zh:"信任", example:"Trust is important in any friendship.", unit:"relationships" },
  { id:"conflict", word:"conflict", pos:"n.", zh:"衝突", example:"They had a small conflict over the schedule.", unit:"relationships" },
  { id:"apologize", word:"apologize", pos:"v.", zh:"道歉", example:"He apologized for being late.", unit:"relationships" },
  { id:"forgive", word:"forgive", pos:"v.", zh:"原諒", example:"It took her a while to forgive him.", unit:"relationships" },
  { id:"support", word:"support", pos:"n./v.", zh:"支持", example:"My family always supports my decisions.", unit:"relationships" },
  { id:"argue", word:"argue", pos:"v.", zh:"爭吵、爭論", example:"They argue about small things sometimes.", unit:"relationships" },
  { id:"compromise", word:"compromise", pos:"n./v.", zh:"妥協", example:"We reached a compromise after talking it over.", unit:"relationships" },
  { id:"loyal", word:"loyal", pos:"adj.", zh:"忠誠的", example:"He is a loyal friend.", unit:"relationships" },
  { id:"affection", word:"affection", pos:"n.", zh:"喜愛、情感", example:"She showed a lot of affection toward her dog.", unit:"relationships" },
  { id:"breakup", word:"breakup", pos:"n.", zh:"分手", example:"The breakup was difficult for both of them.", unit:"relationships" },
  { id:"commitment", word:"commitment", pos:"n.", zh:"承諾、投入", example:"Marriage requires a lot of commitment.", unit:"relationships" },
  { id:"reunion", word:"reunion", pos:"n.", zh:"重聚", example:"Our class reunion is next month.", unit:"relationships" },
  { id:"bond", word:"bond", pos:"n.", zh:"羈絆、連結", example:"They share a strong bond as siblings.", unit:"relationships" },
  { id:"betray", word:"betray", pos:"v.", zh:"背叛", example:"He felt betrayed when his friend told his secret.", unit:"relationships" },
  { id:"sincere", word:"sincere", pos:"adj.", zh:"真誠的", example:"Her apology sounded very sincere.", unit:"relationships" },
  { id:"mutual", word:"mutual", pos:"adj.", zh:"互相的", example:"They have mutual respect for each other.", unit:"relationships" },
  { id:"empathy", word:"empathy", pos:"n.", zh:"同理心", example:"Good friends show empathy when you're struggling.", unit:"relationships" },
  { id:"reconcile", word:"reconcile", pos:"v.", zh:"和解", example:"The two friends finally reconciled after months apart.", unit:"relationships" },
  { id:"comfort", word:"comfort", pos:"n./v.", zh:"安慰", example:"She tried to comfort her friend after the bad news.", unit:"relationships" },

  // ---- 娛樂 ----
  { id:"concert", word:"concert", pos:"n.", zh:"演唱會", example:"We're going to a concert this weekend.", unit:"entertainment" },
  { id:"ticket", word:"ticket", pos:"n.", zh:"票", example:"I bought two tickets for the show.", unit:"entertainment" },
  { id:"audience", word:"audience", pos:"n.", zh:"觀眾", example:"The audience cheered loudly.", unit:"entertainment" },
  { id:"performance", word:"performance", pos:"n.", zh:"表演", example:"Her performance on stage was amazing.", unit:"entertainment" },
  { id:"exhibition", word:"exhibition", pos:"n.", zh:"展覽", example:"We visited an art exhibition downtown.", unit:"entertainment" },
  { id:"celebrity", word:"celebrity", pos:"n.", zh:"名人", example:"A famous celebrity showed up at the event.", unit:"entertainment" },
  { id:"entertainment", word:"entertainment", pos:"n.", zh:"娛樂", example:"Movies are a popular form of entertainment.", unit:"entertainment" },
  { id:"boring", word:"boring", pos:"adj.", zh:"無聊的", example:"The movie was a little boring.", unit:"entertainment" },
  { id:"exciting", word:"exciting", pos:"adj.", zh:"令人興奮的", example:"The game was really exciting.", unit:"entertainment" },
  { id:"thrilling", word:"thrilling", pos:"adj.", zh:"刺激的", example:"The roller coaster ride was thrilling.", unit:"entertainment" },
  { id:"comedy", word:"comedy", pos:"n.", zh:"喜劇", example:"I love watching comedy shows.", unit:"entertainment" },
  { id:"drama", word:"drama", pos:"n.", zh:"戲劇", example:"She's watching a new drama series.", unit:"entertainment" },
  { id:"album", word:"album", pos:"n.", zh:"專輯", example:"Their new album comes out next week.", unit:"entertainment" },
  { id:"soundtrack", word:"soundtrack", pos:"n.", zh:"配樂、原聲帶", example:"The movie's soundtrack was beautiful.", unit:"entertainment" },
  { id:"applause", word:"applause", pos:"n.", zh:"掌聲", example:"The performance ended with loud applause.", unit:"entertainment" },
  { id:"rehearsal", word:"rehearsal", pos:"n.", zh:"排練", example:"We have one more rehearsal before the show.", unit:"entertainment" },
  { id:"costume", word:"costume", pos:"n.", zh:"戲服", example:"Her costume for the play looked amazing.", unit:"entertainment" },
  { id:"script", word:"script", pos:"n.", zh:"劇本", example:"The actors memorized the whole script.", unit:"entertainment" },
  { id:"plot", word:"plot", pos:"n.", zh:"劇情", example:"The plot of the movie was confusing.", unit:"entertainment" },
  { id:"genre", word:"genre", pos:"n.", zh:"類型（作品）", example:"Mystery is my favorite genre of book.", unit:"entertainment" },
];

const PASSAGES = [
  {
    id: "p-daily",
    unit: "daily",
    title: "A Typical Weekday",
    level: 1,
    text: "Every weekday, my **alarm** rings at six thirty. I follow the same **routine**: I get up, eat a quick **breakfast**, and start my **commute** to work. The bus ride takes almost an hour, so I usually read or listen to music. After work, I still have several **chores** to do, like washing dishes and doing the laundry. Some days I also need to run an **errand**, such as picking up medicine from the pharmacy. By the time I finish everything, I feel completely **exhausted**. I try to keep a simple **schedule** so my apartment stays **tidy** and my life doesn't feel too busy. On weekends, I finally have time to **relax** and do nothing at all."
  },
  {
    id: "p-school",
    unit: "school",
    title: "Exam Week",
    level: 2,
    text: "This week is exam week, and every **classmate** in my class looks stressed. We each have a full **schedule** of tests, and it's hard to **focus** for so many hours. Before each **exam**, I like to **review** my notes and **memorize** key vocabulary. My teacher gave us a difficult **assignment** last **semester**, and now half of the questions come from that same **textbook** chapter. I also have an **essay** due tomorrow, and the **deadline** for my **presentation** is right after that. It's tiring, but I know that if I keep my **motivation** high and try to **improve** a little every day, my **grade** will get better."
  },
  {
    id: "p-food",
    unit: "food",
    title: "Dinner at a New Restaurant",
    level: 1,
    text: "Last night, my friends and I tried a new **restaurant** downtown. We didn't make a **reservation**, so we had to wait fifteen minutes for a table. When the **menu** arrived, everything sounded **delicious**, but I couldn't decide because I had a big **appetite**. I finally ordered a **spicy** noodle dish with **fresh** vegetables. The **portion** was huge, so I had **leftovers** to bring home. For **dessert**, we shared a small chocolate cake. When the **waiter** brought the **bill**, we were surprised that it wasn't very expensive. Next time, I might just order **takeout** instead, since parking was difficult."
  },
  {
    id: "p-travel",
    unit: "travel",
    title: "Planning a Trip",
    level: 2,
    text: "Before every **journey**, I like to make a detailed **itinerary** so I don't waste time deciding where to go each day. This time, our **destination** is a small coastal town known for its beautiful **scenery**. I already packed my **luggage**, checked my **passport**, and bought some local **currency**. We booked our **accommodation** near the train station, so **transportation** should be easy. My favorite part of any trip is **sightseeing** and trying new food, since it helps me understand the local **culture**. I also want to bring back a small **souvenir** for my family. Even though **jet lag** can be uncomfortable, I'm excited for this **adventure**."
  },
  {
    id: "p-feelings",
    unit: "feelings",
    title: "How I Feel Today",
    level: 2,
    text: "This morning I felt a little **nervous** before my presentation, but I tried to stay **calm**. My best friend is always **confident** in front of a crowd, and I admire how **patient** she is when things go wrong. I can be quite **stubborn** sometimes, especially when I think I'm right, but I'm working on being more **generous** and open to other people's ideas. I used to feel **jealous** when my classmates did better than me, but now I try to feel **grateful** for my own progress instead. Public speaking still makes me **anxious**, and I sometimes feel **embarrassed** if I forget my words. Still, I stay **optimistic**, because I know I'll become more **cheerful** and less **shy** over time."
  },
  {
    id: "p-work",
    unit: "work",
    title: "My First Job Interview",
    level: 3,
    text: "Yesterday I had my first job **interview** after finishing my **internship**. I updated my **resume** the night before and practiced answering questions about my **experience** and **qualifications**. The interviewer asked about my long-term career **goals** and how I handle **teamwork**. I explained that I'm ready for new **challenges** and that I hope to build good relationships with my future **colleagues**. We also talked about **salary** and the possibility of a **promotion** after one year. I mentioned that I enjoy taking on **responsibility** and that I'm looking for an **opportunity** to grow. I left feeling proud of my **achievement**, even if I don't get the job — just having the interview was already a great experience."
  },
  {
    id: "p-health",
    unit: "health",
    title: "A Trip to the Clinic",
    level: 2,
    text: "Yesterday I woke up with a bad **headache** and a slight **fever**, so I decided to visit the clinic for a **checkup**. The doctor asked about my **symptoms** and checked whether I had any **allergy**. After a quick **diagnosis**, she gave me a **prescription** and told me to pick it up at the **pharmacy** nearby. She also reminded me to **hydrate** well, get enough **sleep**, and reduce my **stress** level. I've had a minor knee **injury** from running, so she suggested a short **therapy** session to help me **recover** faster. Overall, she said my **immune** system is strong, and with a little rest and better **posture** at my desk, I should feel like myself again soon."
  },
  {
    id: "p-tech",
    unit: "tech",
    title: "My Phone Won't Turn On",
    level: 3,
    text: "This morning, my **device** wouldn't turn on, and I panicked because I hadn't made a **backup** in weeks. I checked the **charger** and the **battery**, but the **screen** stayed black. I tried restarting it and installing the newest **software** **update**, and it finally turned back on. Then a strange **notification** appeared saying possible **malware** had been detected, so I quickly changed my **password** and cleared some files to free up **storage**. My **wireless** connection was also weak, which explained why my **browser** kept freezing whenever I opened a shopping **application**. Before I could **upload** my photos or **download** anything else, I decided to check my home **bandwidth** instead."
  },
  {
    id: "p-shopping",
    unit: "shopping",
    title: "Weekend Shopping",
    level: 2,
    text: "I went shopping this weekend to look for a new jacket within my **budget**. The store was having a big **discount**, and I also had a **coupon** from an email. At the **checkout**, the **cashier** scanned my items and printed a **receipt**. I noticed the **quality** of the fabric was better than I expected for the price — a real **bargain**. A week later, the sleeves felt too short, so I brought it back for an **exchange**. The store didn't have my size in stock, so they offered a **refund** instead and said the new **inventory** would arrive with the next **delivery**. I decided to try their online store, where I could track my **package** and even sign up for a monthly **subscription** for future **purchases**."
  },
  {
    id: "p-nature",
    unit: "nature",
    title: "Extreme Weather",
    level: 3,
    text: "The weather **forecast** this week predicted a **thunderstorm**, but instead we got a light **drizzle** followed by a cool **breeze**. Last month, a serious **drought** dried up several rivers, and just two years ago, a **flood** damaged many homes near the coast. Scientists say the rising **temperature** is affecting the local **ecosystem** and putting some **wildlife** at risk of losing their natural **habitat**. Our town has started several **sustainable** projects, like teaching people to **recycle** and reduce **pollution**. During harvest season, farmers check the **tide** schedule if their fields are near the coast, since strong waves can affect the **harvest**. Understanding **climate** patterns helps everyone prepare for the future, even for rare events like a **volcano** eruption or a sudden winter **blizzard**."
  },
  {
    id: "p-relationships",
    unit: "relationships",
    title: "Making Up After an Argument",
    level: 3,
    text: "Last week, my best friend and I started to **argue** about something small, and it turned into a real **conflict**. At first, neither of us wanted to **compromise**, and I could feel the **trust** between us getting weaker. After a few days, I decided to **apologize**, because our **relationship** means a lot to me. She was willing to **forgive** me, and we talked honestly about how to give each other more **support** in the future. I realized how much I value her **loyal** friendship and the **affection** we have for each other. We agreed to be more **sincere** and to show more **empathy** before jumping to conclusions. In the end, our little **reunion** over coffee helped us **reconcile**, and I felt real **comfort** knowing our **bond** was still strong."
  },
  {
    id: "p-entertainment",
    unit: "entertainment",
    title: "Concert Night",
    level: 3,
    text: "I went to a **concert** last night after buying my **ticket** weeks in advance. The **audience** was huge, and the **performance** was even better than I expected. Before the show, there was a small art **exhibition** in the lobby featuring photos of the **celebrity** headliner. I love this kind of **entertainment** because it's never **boring** — every song felt **exciting** and even a little **thrilling**. Between songs, the band told a few jokes, almost like a mini **comedy** show, before returning to more serious **drama** in their lyrics. I later found out their new **album** and its **soundtrack** took two years to finish. When the final song ended, the **applause** lasted almost five minutes. I heard they only had one **rehearsal** the day before, which is impressive, especially with such elaborate **costume** changes and careful **script** planning throughout the whole **plot** of the show — closer to a theater **genre** than a normal concert."
  },
];
